# Generated by Django 5.0.3 on 2024-03-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Python', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'description')},
        ),
    ]
